In [1]:
t = ('a', 'b')  # 튜플 생성
t = t + ('c',)  # 'c'를 포함한 새 튜플로 갱신
print(t)  # 출력: ('a', 'b', 'c')

('a', 'b', 'c')


In [2]:
def print_nxn_square(n):
    """
    정수 n을 입력받아 n x n 크기의 숫자 사각형을 출력합니다.
    숫자는 1부터 n*n까지 순서대로 채워집니다.

    Args:
        n (int): 사각형의 크기를 결정하는 정수. (n > 0)
    """
    if n <= 0:
        print("n은 0보다 큰 정수여야 합니다.")
        return

    # 숫자를 1부터 n*n까지 순서대로 채우기 위한 변수
    num = 1

    # n행 n열 사각형 출력
    for row in range(n):
        for col in range(n):
            # 숫자를 출력하고, 다음 숫자로 증가
            # end=" "를 사용하여 한 칸 띄우고 다음 숫자를 같은 줄에 출력
            # {:<4}는 숫자를 4칸 너비로 왼쪽 정렬하여 출력 (보기 좋게 하기 위함)
            print(f"{num:<4}", end="")
            num += 1
        # 한 행의 출력이 끝나면 다음 줄로 이동
        print()

# --- 사용 예시 ---
# n이 3일 때
print("n = 3")
print_nxn_square(3)
print("\n" + "="*30 + "\n") # 구분선

# n이 4일 때
print("n = 4")
print_nxn_square(4)
print("\n" + "="*30 + "\n")

# n이 5일 때
print("n = 5")
print_nxn_square(5)
print("\n" + "="*30 + "\n")

# 잘못된 입력 예시
print("n = 0")
print_nxn_square(0)

n = 3
1   2   3   
4   5   6   
7   8   9   


n = 4
1   2   3   4   
5   6   7   8   
9   10  11  12  
13  14  15  16  


n = 5
1   2   3   4   5   
6   7   8   9   10  
11  12  13  14  15  
16  17  18  19  20  
21  22  23  24  25  


n = 0
n은 0보다 큰 정수여야 합니다.


In [4]:
import numpy as np

def create_nxn_matrix(n):
    """
    정수 n을 입력받아 1부터 n*n까지 채워진 n x n 크기의 넘파이 배열을 생성합니다.
    """
    if n <= 0:
        print("n은 0보다 큰 정수여야 합니다.")
        return None

    # 1부터 n*n까지의 숫자를 담은 1차원 배열 생성
    flat_array = np.arange(1, n*n + 1)

    # 1차원 배열을 n x n 크기로 재구성 (reshape)
    nxn_matrix = flat_array.reshape(n, n)
    return nxn_matrix

# n=4일 때 4x4 행렬 생성
n_value = 4
matrix_4x4 = create_nxn_matrix(n_value)

print(f"--- n={n_value}일 때의 4x4 행렬 ---")
print(matrix_4x4)

# 4x4 행렬을 1차원 형태로 변환 (reshape 사용)
# -1은 numpy가 자동으로 해당 차원의 크기를 계산하도록 합니다.
# 이 경우, 1차원으로 변환하므로 (n*n,) 형태가 됩니다.
reshaped_1d_array = matrix_4x4.reshape(-1)

print(f"\n--- {n_value}x{n_value} 행렬을 1차원으로 변환한 결과 ---")
print(reshaped_1d_array)
print(f"변환된 배열의 차원: {reshaped_1d_array.shape}")

--- n=4일 때의 4x4 행렬 ---
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

--- 4x4 행렬을 1차원으로 변환한 결과 ---
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
변환된 배열의 차원: (16,)


In [5]:
# 2025 06 24 filter practice
import os
os.environ['QT_QPA_PLATFORM'] = 'xcb'
import cv2
import numpy as np

img = cv2.imread('lena.png',cv2.IMREAD_GRAYSCALE)

print(f"원본 이미지 shape (그레이스케일): {img.shape}") # 예: (512, 512)

# 2. 첫 번째 차원 확장: (h, w) -> (h, w, c) 형태로 만들기
# 그레이스케일 이미지는 채널이 1개이므로, 마지막에 1을 추가합니다.
# axis=-1 또는 axis=2는 마지막 차원에 1을 추가하라는 의미입니다.
img_hwc = np.expand_dims(img, axis=-1)
print(f"expand_dims 후 (h, w, c): {img_hwc.shape}") # 예: (512, 512, 1)

# 3. 두 번째 차원 확장: (h, w, c) -> (batch, h, w, c) 형태로 만들기
# 배치 차원 (첫 번째 차원)에 1을 추가합니다.
# axis=0은 첫 번째 차원에 1을 추가하라는 의미입니다.
img_batch_hwc = np.expand_dims(img_hwc, axis=0)
print(f"expand_dims 후 (batch, h, w, c): {img_batch_hwc.shape}") # 예: (1, 512, 512, 1)

print("\n--- 다른 방법: reshape 활용 ---")

# 4. (h, w) 형태를 한 번에 (1, h, w, 1) 형태로 reshape
# 그레이스케일 이미지 (H, W) -> (1, H, W, 1)
# -1은 numpy가 자동으로 해당 차원의 크기를 계산하도록 합니다.
# 이 경우 H*W = 512*512 = 262144 이므로, (1, 512, 512, 1) 로 재구성합니다.
img_reshaped_batch_hwc = img.reshape(1, img.shape[0], img.shape[1], 1)
print(f"reshape 후 (batch, h, w, c): {img_reshaped_batch_hwc.shape}")

# 두 결과가 동일한지 확인
print(f"expand_dims와 reshape 결과가 동일한가? {np.array_equal(img_batch_hwc, img_reshaped_batch_hwc)}")



원본 이미지 shape (그레이스케일): (512, 512)
expand_dims 후 (h, w, c): (512, 512, 1)
expand_dims 후 (batch, h, w, c): (1, 512, 512, 1)

--- 다른 방법: reshape 활용 ---
reshape 후 (batch, h, w, c): (1, 512, 512, 1)
expand_dims와 reshape 결과가 동일한가? True


In [6]:
import numpy as np
import os

image_path = 'lena.png'

if not os.path.exists(image_path):
    print(f"오류: '{image_path}' 파일을 찾을 수 없습니다.")
    print("예시 이미지 파일(lena.png 등)을 현재 스크립트와 같은 디렉토리에 넣어주세요.")
    print("\nColab 환경이라면 다음 코드를 실행하여 lena.png를 다운로드할 수 있습니다:")
    print("!wget -O lena.png https://raw.githubusercontent.com/opencv/opencv/master/samples/data/lena.png")
    exit()

img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

if img is None:
    print(f"오류: '{image_path}' 이미지를 로드할 수 없습니다. 파일이 손상되었거나 형식이 지원되지 않을 수 있습니다.")
    exit()

print(f"**원본 이미지 shape (그레이스케일): {img.shape}") # 예: (512, 512)

# 1. 첫 번째 차원 확장: (h, w) -> (h, w, c) 형태로 만들기
img_hwc = np.expand_dims(img, axis=-1)
print(f"**expand_dims 후 (h, w, c): {img_hwc.shape}") # 예: (512, 512, 1)

# 2. 두 번째 차원 확장: (h, w, c) -> (batch, h, w, c) 형태로 만들기
img_batch_hwc = np.expand_dims(img_hwc, axis=0)
print(f"**expand_dims 후 (batch, h, w, c): {img_batch_hwc.shape}") # 예: (1, 512, 512, 1)

print("\n--- 다른 방법: reshape 활용 ---")

# (h, w) 형태를 한 번에 (1, h, w, 1) 형태로 reshape
img_reshaped_batch_hwc = img.reshape(1, img.shape[0], img.shape[1], 1)
print(f"**reshape 후 (batch, h, w, c): {img_reshaped_batch_hwc.shape}")

**원본 이미지 shape (그레이스케일): (512, 512)
**expand_dims 후 (h, w, c): (512, 512, 1)
**expand_dims 후 (batch, h, w, c): (1, 512, 512, 1)

--- 다른 방법: reshape 활용 ---
**reshape 후 (batch, h, w, c): (1, 512, 512, 1)
