In [2]:
# 2025 06 24 filter practice
import os
os.environ['QT_QPA_PLATFORM'] = 'xcb'
import cv2
import numpy as np

img = cv2.imread('lena.png',cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1,1,1],[1,-8,1],[1,1,1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge',output)
cv2.waitKey(0)
cv2.destroyAllWindows()

print("close.")

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]
close.


In [1]:
import cv2
import numpy as np

img = cv2.imread('lena.png',cv2.IMREAD_GRAYSCALE)
# 리스트를 np.array()로 감싸고, 그 결과에 1/16을 곱합니다.
kernel = (1/16) * np.array([[1,2,1],[2,4,2],[1,2,1]], dtype=np.float32)
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge',output)
cv2.waitKey(0)
cv2.destroyAllWindows()

print("close.")

[[0.0625 0.125  0.0625]
 [0.125  0.25   0.125 ]
 [0.0625 0.125  0.0625]]


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/hsm/python_ai/intro/.venv/lib/python3.10/site-packages/cv2/qt/plugins"


close.
